version: '3'

services:
  crud-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rolisangor/crud-app
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST_URL=jdbc:postgresql://db:5432/crud_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
    ports:
      - 9000:9000

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crud_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8383:8080

volumes:
  postgres-data:
    driver: local